# Generated by Django 6.0.5 on 2026-06-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_safaripackage_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
