# Generated by Django 6.0.5 on 2026-05-10 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public'), ('USER', 'Registered User'), ('SUBADMIN', 'Sub-Admin'), ('SUPERADMIN', 'Super Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VISITOR', 'Visitor'), ('USER', 'User'), ('SUBADMIN', 'Sub-Admin'), ('SUPERADMIN', 'Super Admin')], max_length=20)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('special_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='inventory.module')),
            ],
            options={
                'unique_together': {('module', 'role')},
            },
        ),
    ]
