# Generated by Django 6.0.5 on 2026-06-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('hero_image', models.URLField(blank=True, max_length=500, null=True)),
                ('best_travel_season', models.CharField(blank=True, max_length=200, null=True)),
                ('visa_information', models.TextField(blank=True, null=True)),
                ('health_requirements', models.TextField(blank=True, null=True)),
                ('featured_wildlife', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafariLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activities', models.TextField(blank=True, null=True)),
                ('wildlife', models.TextField(blank=True, null=True)),
                ('featured_image', models.URLField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='destinations.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('LODGE', 'Luxury Lodge'), ('CAMP', 'Tented Camp'), ('VILLA', 'Private Villa'), ('HOTEL', 'Hotel')], default='LODGE', max_length=20)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(default=20)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField(blank=True, null=True)),
                ('featured_image', models.URLField(blank=True, max_length=500, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.safarilocation')),
            ],
        ),
    ]
