# Generated by Django 6.0.5 on 2026-06-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='destinations/heroes/'),
        ),
        migrations.AlterField(
            model_name='safarilocation',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
